### ISSUE TITLE
How to use the colorlist and more than 4 Dimensions?

### ISSUE THREAD

**Issue by opiekuny** [stred/com_capventis_SunburstQuadrant#1]
Hi Stephen,
we really like your extension "SunburstQuadrant" and would like to know, 
how we can use the color List?
how can we add more than 4 dimensions?

Best reagrds!

**Comment by stred** [comment]
You can have as many dimensions as you like. You would just have to adjust to colour handling code to use a list instead of, or in addition to, the static four options.
